/* This file is autogenerated -- do not edit. */

/* Extra include files. */

/* Declare test functions. */
void testAssertOk();
void testAssertFail();
void testIgnore();
void testFailExplicit();
void testAssertEqOk();
void testAssertIntFail();
void testAssertHexFail();
void testAssertStrFail();
void testAssertParam(int x);
void testDump();
void testFixtureOk();
void testFixtureFail();
void testFixtureIgnore();

/* Declare test stubs. */
static void testAssertParam_stub_0000(void) { testAssertParam(0); }
static void testAssertParam_stub_0001(void) { testAssertParam(1); }
static void testAssertParam_stub_0002(void) { testAssertParam(2); }

/* Declare fixture functions. */
void dumper(void);
void setup(void);
void teardown(void);

/* Declare filenames once. */
const char* FN_0000 = "test-all.c";
const char* FN_0001 = "test-dump.c";
const char* FN_0002 = "test-fixture.c";

/* Call our test functions. */
void runTests(void) {
	tinytest_run_test(testAssertOk, FN_0000, 3, "testAssertOk()");
	tinytest_run_test(testAssertFail, FN_0000, 6, "testAssertFail()");
	tinytest_run_test(testIgnore, FN_0000, 9, "testIgnore()");
	tinytest_run_test(testFailExplicit, FN_0000, 14, "testFailExplicit()");
	tinytest_run_test(testAssertEqOk, FN_0000, 18, "testAssertEqOk()");
	tinytest_run_test(testAssertIntFail, FN_0000, 23, "testAssertIntFail()");
	tinytest_run_test(testAssertHexFail, FN_0000, 26, "testAssertHexFail()");
	tinytest_run_test(testAssertStrFail, FN_0000, 29, "testAssertStrFail()");
	tinytest_run_test(testAssertParam_stub_0000, FN_0000, 36, "testAssertParam(0)");
	tinytest_run_test(testAssertParam_stub_0001, FN_0000, 37, "testAssertParam(1)");
	tinytest_run_test(testAssertParam_stub_0002, FN_0000, 38, "testAssertParam(2)");
	tinytest_set_dump(dumper);
	tinytest_run_test(testDump, FN_0001, 7, "testDump()");
	tinytest_set_dump(NULL);
	tt_register_fixture(setup, teardown);
	tinytest_run_test(testFixtureOk, FN_0002, 6, "testFixtureOk()");
	tinytest_run_test(testFixtureFail, FN_0002, 7, "testFixtureFail()");
	tinytest_run_test(testFixtureIgnore, FN_0002, 8, "testFixtureIgnore()");
	tt_register_fixture(NULL, NULL);
}

